setwd('F:/R/abundance_data')
library(edgeR)
x<-read.delim("count20_40.txt",header=T, sep = "\t") 
y<-DGEList(counts=x[,2:7], genes=x[,1]) 
keep<-rowSums(cpm(y)>1)>=4
y <- y[keep, , keep.lib.sizes=FALSE]
y<-DGEList(counts=y$counts,genes=y$genes)
y<-plotMDS(y) 
group <- factor(c(1,1,1,2,2,2))
y <- DGEList(counts=x[,2:7],group=group)
y<-calcNormFactors(y)
design <- model.matrix(~group)
y <- estimateDisp(y,design)
fit <- glmQLFit(y, design)
qlf <- glmQLFTest(fit, coef =2 )
FDR <- p.adjust(qlf$table$PValue, method="BH")
write("FDR < 0.05",'num_count_40.txt')
write(sum(FDR < 0.05),'num_count_40.txt',append = TRUE)
#pdf('md_qlf_30.pdf')
#plotMD(qlf)
result = data.frame(x$id,qlf$table,FDR)
write(summary(de<-decideTestsDGE(qlf)), 'num_count_40.txt',append=TRUE)
write.csv(result, "count_40.csv")
#detags<-rownames(y)[as.logical(de)]
#pdf('qlf_30.pdf')
#plotSmear(qlf, de.tags=detags)
#abline(h=c(-4,4),col="blue") 
#dev.off()
